### ISSUE TITLE
Export methods

### ISSUE THREAD

**Issue by cloudlena** [eefret/gravatar#1]
There are a couple of methods that currently aren't being exported by the package but I think only make sense if they are exported (E.g. `Gravatar.setSize` or `Gravatar. setDefaultImage`). Could you please export them?

**Comment by eefret** [comment]
sure, probably a mistake, kinda noob in Go back then

**Comment by eefret** [comment]
fixed on 6c5d9d4

**Comment by cloudlena** [comment]
Nice. Thanks, @eefret!
